### ISSUE TITLE
ElementPicker search by multi-digit atomic number shows result from first digit

### ISSUE THREAD

**Issue by Aprillion** [HorusGoul/atom-pwa#27]
**Describe the bug**
When searching for an element in ElementPicker by the atomic number, the results can get out of sync with the search field value.

**To Reproduce**
1. Go to https://atom.horuslugo.com/mass-calculator
2. Click on `Add element`
3. Type `25`
4. See `Helium`

**Expected behavior**
It should find `Manganese`.

**Screenshots**
![image](https://user-images.githubusercontent.com/1087670/109385236-b04a2500-78f2-11eb-8939-f35e3ffb7fbd.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox
 - Version: 87
 

**Additional context**

Discovered when adding a test in https://github.com/OpenSourceRaidGuild/atom-pwa/pull/43 and currently the failing test is skipped => we need to unskip the test when fixed.

**Comment by HorusGoul** [comment]
Thanks for the report, @Aprillion. The issue has been fixed!
